config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  #sessions 
  get 'login', to: 'sessions#new', as: "login"
  post "login", to: "sessions#create"
  delete 'login', to: 'sessions#destroy', as: 'logout'

  #trips
  resources :trips
  post '/trips/:id/add_driver', to: "trips#add_driver", as: 'add_driver'
  post '/trips/:id/add_passenger', to: "trips#add_passenger", as: 'add_passenger'
  
  delete '/trips/:id/destroy_passenger', to: "trips#destroy_passenger", as: 'destroy_passenger'
  delete '/trips/:id/destroy_driver', to: "trips#destroy_driver", as: 'destroy_driver'

  #locations
  resources :locations, only: [:show, :index]

  #users
  get '/home', to: 'users#home'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, except: [:new]

  #cars
  resources :cars
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#home'
end

app/models/trip.rb
class Trip < ApplicationRecord
#================ ASSOCIATIONS =================================
  has_many :driver_relationships, dependent: :destroy
  has_many :drivers, through: :driver_relationships, source: :user
  has_many :passenger_relationships, dependent: :destroy
  has_many :passengers, through: :passenger_relationships, source: :user

  has_many :cars, through: :driver_relationships
  belongs_to :location

#================ HELPERS =======================================

  def display
    self.location.name + " " + '|' + " " + self.date_display
  end

  def organizer_full_name
    self.drivers.first.full_name
  end

  def total_seats
    total = 0
    self.cars.each do |car|
     total += car.num_of_seats 
    end
    total
  end

  def available_seats
    total_seats - (self.passengers.count + self.drivers.count)
  end
  # def cars
  #   self.driver_relationships.map {|dr| dr.car }
  # end

  def date_display
    self.date.strftime("%A, %d %b %Y")
  end

  def d_time
    self.departure_time.strftime("%I:%M %p")
  end

  def r_time
    self.return_time.strftime("%I:%M %p")
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :authorize
    before_action :find_trip, except: [:index, :new, :create]
    before_action :users_cars, only: [:edit, :new]
    
    def index
        @trips = Trip.all
    end

    def show
        @current_user = current_user
    end

    def new
        @trip = Trip.new
        @user = current_user
    end

    def edit
    end

    def create
        @trip = Trip.new(trip_params(:location_id, :date, :description, :departure_time, :return_time))
    
        if @trip.save
          @dr = DriverRelationship.create(trip: @trip, user: current_user)
            @dr.update(trip_params(:car_id))
            redirect_to @trip
        else
            render 'new'
        end
    end

    def update
        if @trip.update(trip_params)
            redirect_to @trip
        else
            render 'edit'
        end
    end

    def add_passenger
        PassengerRelationship.create(user: current_user, trip: @trip) 
        redirect_to trip_path(@trip)
    end

    def add_driver
        @dr = DriverRelationship.new(user: current_user, trip: @trip) 
        @dr.update(trip_params(:car_id))
        redirect_to trip_path(@trip)
    end

    def destroy_passenger
        @pr = PassengerRelationship.find_by(user: current_user, trip: @trip)
        @pr.destroy
        redirect_to @trip
    end

    def destroy_driver
        @dr = DriverRelationship.find_by(user: current_user, trip: @trip)
        @dr.destroy
        redirect_to @trip
    end

    def destroy
        @trip.destroy
        redirect_to home_path
    end

    private

    def users_cars
        @cars = current_user.cars
    end

    def trip_params(*args)
        params.require(:trip).permit(*args)
    end

    def find_trip
        @trip = Trip.find(params[:id])
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_dbuttons.html.erb
<% if !@current_user.is_driver?(@trip) && !@current_user.is_passenger?(@trip) && @current_user.has_car? %>
<%= form_with model: @trip, url: add_driver_path(@trip), method: 'post' do |f| %>
    <%= f.label "Select Car to Join Trip"%><br />
    <%= f.collection_select :car_id, @current_user.cars, :id, :make_and_model %><br />

    <%= f.submit "Join as a Driver"%>
<% end %>

<% elsif @current_user.is_driver?(@trip) && !@current_user.is_organizer?(@trip) %>
<%= button_to "Leave Trip", destroy_driver_path(@trip), method: :delete %>
<% end %>

app/views/trips/_form.html.erb
<%= form_with model: @trip do |f| %>

    <% if @trip.errors.any? %>
        <div id="error_explanation">
         <h2>
            <%= pluralize(@trip.errors.count, "error") %> prohibited
            you from creating the trip:
         </h2>
         <ul>
          <% @trip.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
         </ul>
        </div>
    <% end %>


    <p>
    <%= f.label :location %><br />
    <%= f.collection_select :location_id, Location.all, :id, :name, prompt: true%>
    </p>

    <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, placeholder: "Meeting point, shopping list, planned activities, etc." %>
    </p>

    <p>
    <%= f.label :date %><br />
    <%= f.date_field :date, required: true %>
    </p>

    <p>
    <%= f.label :car %><br />
    <%= f.collection_select :car_id, @cars, :id, :make_and_model %>
    </p>

    <p>
    <%= f.label :departure_time %><br />
    <%= f.time_field :departure_time, required: true %>
    </p>

    <p>
    <%= f.label :return_time %><br />
    <%= f.time_field :return_time, required: true %>
    </p>

    <%= f.submit %>
<% end %>

app/views/trips/_obuttons.erb
<%= button_to "Update", edit_trip_path(@trip), method: :get %> | <%= button_to "Cancel Trip", trip_path(@trip), method: :delete %>

app/views/trips/_pbuttons.html.erb
<% if !@current_user.is_driver?(@trip) && !@current_user.is_passenger?(@trip) %>
<%= button_to "Join as a Passenger", add_passenger_path(@trip) %>

<% elsif @current_user.is_passenger?(@trip) %>
<%= button_to "Leave Trip", destroy_passenger_path(@trip), method: :delete  %>
<% end %>

app/views/trips/edit.html.erb
<h1>Edit a Trip</h1>

<%= render 'form' %>

app/views/trips/index.html.erb
<h1>All Trips</h1>
<% @trips.each do |trip| %>
<div>
   <%=link_to trip.display, trip_path(trip) %> <br />
    <label>Organizer: </label> <%= trip.organizer_full_name %><br /><br />
</div>
<% end %>

app/views/trips/new.html.erb
<h1>Plan a Trip</h1>
<% if @user.has_car? %>
<%= render 'form' %>
<% else %>
<h2>Please <%= link_to "add a Car", new_car_path %> to Plan Trip</h2>
<% end %>

app/views/trips/show.html.erb
<h1><%= @trip.location.name%></h1>
<h5><%= @trip.date_display %></h5>

<% if @current_user.is_organizer?(@trip) %>
    <%= render 'obuttons'%>
<% end %>
<br />
<br />
<label>Departure Time:</label>
<%= @trip.d_time %>
<br />
<label>Return Time:</label>
<%= @trip.r_time %>
<br /><br />

<p>Available Seats: <%= @trip.available_seats %></p>

<h4>Organizer: <%= @trip.organizer_full_name %></h4>
<br />

<h4>Trip Description:</h4>
<p><%= @trip.description %></p>
<br/>

<h4>Drivers:</h4>
<ul> <% @trip.drivers.each do |driver| %>
    <li><%=driver.full_name%></li>
<% end %> 
</ul> <%# working on excluding organizer in Driver %>
<br />

<%= render 'dbuttons'%>
<br />

<h4>Passengers:</h4>
<ul> <% @trip.passengers.each do |passenger| %>
    <li><%=passenger.full_name%></li>
<% end %>
</ul>

<%= render 'pbuttons'%>