config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  #sessions 
  get 'login', to: 'sessions#new', as: "login"
  post "login", to: "sessions#create"
  delete 'login', to: 'sessions#destroy', as: 'logout'

  #trips
  resources :trips
  post '/trips/:id/add_driver', to: "trips#add_driver", as: 'add_driver'
  post '/trips/:id/add_passenger', to: "trips#add_passenger", as: 'add_passenger'
  
  delete '/trips/:id/destroy_passenger', to: "trips#destroy_passenger", as: 'destroy_passenger'
  delete '/trips/:id/destroy_driver', to: "trips#destroy_driver", as: 'destroy_driver'

  #locations
  resources :locations, only: [:show, :index]

  #users
  get '/home', to: 'users#home'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, except: [:new]

  #cars
  resources :cars
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#home'
end

app/models/car.rb
class Car < ApplicationRecord
#================= Associations ===================== 
  belongs_to :user

#================= Validations ===================== 
  validates :num_of_seats, presence: true, numericality: { only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 8}

#================= Helpers ===================== 

  def make_and_model
    self.make + ' ' + self.model
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :authorize
    before_action :find_car, except: [:new, :index, :create]

    def index
        @cars = current_user.cars
    end

    def show
    end

    def new
        @car = Car.new
    end

    def edit
    end

    def create
        @car = Car.new(car_params)
        @car.user = current_user
        if @car.save
            redirect_to @car
        else
            render 'new'
        end
    end

    def update
        if @car.update(car_params)
            redirect_to @car
        else
            render 'edit'
        end
    end

    def destroy
        @car.destroy
        redirect_to cars_path
    end

    private

    def car_params
        params.require(:car).permit(:make, :model, :year, :color, :license, :num_of_seats)
    end

    def find_car
        @car = Car.find(params[:id])
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with model: @car do |f| %>
       
    <% if @car.errors.any? %>
        <div id="error_explanation">
         <h2>
            <%= pluralize(@car.errors.count, "error") %> prohibited
            you from adding this car:
         </h2>
         <ul>
          <% @car.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
         </ul>
        </div>
    <% end %>

    <p>
    <%= f.label :make %><br />
    <%= f.text_field :make, placeholder: "Make" %>
    </p>

    <p>
    <%= f.label :model %><br />
    <%= f.text_field :model, placeholder: "Model" %>
    </p>

    <p>
    <%= f.label :year %><br />
    <%= f.text_field :year, placeholder: "Year" %>
    </p>

    <p>
    <label>Number of Seats</label><br />
    <%= f.number_field :num_of_seats, min: 0, max: 8, placeholder: "#", required: true %>
    </p>

    <p>
    <%= f.label :color %><br />
    <%= f.text_field :color, placeholder: "Color" %>
    </p>

    <p>
    <label>License Plate</label><br />
    <%= f.text_field :license, placeholder: "Plate Number", required: true %>
    </p> <%# max 7 length%>

    <%= f.submit %>
<% end %>

app/views/cars/edit.html.erb
<h1>Update Car</h1>

<%= render 'form'%>

app/views/cars/index.html.erb
<h1>Your Cars</h1>
<% @cars.each do |car| %>
    <%= link_to car.make_and_model, car_path(car) %><br /><br/>
    <% end %>

app/views/cars/new.html.erb
<h1>Add a Car</h1>

<%= render 'form'%>

app/views/cars/show.html.erb
<h1><%= @car.make %> | <%= @car.model %></h1>
<label>Year: <%= @car.year %></label><br />
<label>Color: <%= @car.color %></label><br />
<label>License: <%= @car.license %></label><br />