config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  #sessions 
  get 'login', to: 'sessions#new', as: "login"
  post "login", to: "sessions#create"
  delete 'login', to: 'sessions#destroy', as: 'logout'

  #trips
  resources :trips
  post '/trips/:id/add_driver', to: "trips#add_driver", as: 'add_driver'
  post '/trips/:id/add_passenger', to: "trips#add_passenger", as: 'add_passenger'
  
  delete '/trips/:id/destroy_passenger', to: "trips#destroy_passenger", as: 'destroy_passenger'
  delete '/trips/:id/destroy_driver', to: "trips#destroy_driver", as: 'destroy_driver'

  #locations
  resources :locations, only: [:show, :index]

  #users
  get '/home', to: 'users#home'
  get '/signup', to: 'users#new', as: 'signup'
  resources :users, except: [:new]

  #cars
  resources :cars
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#home'
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :trips
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :authorize
   
    def index
        @locations = Location.all
    end

    def show
        @location = Location.find(params[:id])
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/index.html.erb
<h1>Locations:</h1>
<% @locations.all.each do |location| %>
    <h4><%= link_to location.name , location_path(location)%></h4><br />
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<h4>Address: <%=@location.address%></h4>
<br />
<h3>About <%=@location.name%>:</h3>
<p><%=@location.description%></p>

<br />
<%= button_to "Plan a Trip", new_trip_path, method: 'get' %><br />